--- #YAML:1.0
name:               Text-Snippet
version:            0.01
abstract:           TextMate-like snippet functionality
author:
    - Brian Phillips <bphillips@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:  0
    Test::Exception:    0
    Test::More:         0
    Text::Balanced:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
